cluster:
  mkdir -p logs/snakemake/{rule} &&
  sbatch
    --qos={resources.qos}
    --cpus-per-task={threads}
    --mem={resources.mem_mb}
    --job-name=Py-{rule}-{wildcards}
    --output=logs/snakemake/{rule}/{rule}-{wildcards}-%j.out
    --time={resources.time}
default-resources:
  - qos=short
  - nodes=1
  - mem_mb=500
  - time=3
restart-times: 3
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 60
jobs: 500
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
